services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    volumes:
      - /home/inhumano/arr/Files/AppData/Config:/config
      - /home/inhumano/arr/data:/data
    ports:
      - "8080:8080"
    restart: always
