networks:
  default:
    name: homeserver_network

volumes:
  immich_db:

services:
  # --- WATCHTOWER ---
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 1 * *
      - TZ=Europe/Madrid
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=discord://CK-oL_-8_H0yQfGMBq8Nvy7FSJ6jxmdy6M-ZN4Kfg48ymeUHiVI1NBdIiT5pFAbz5Oxy@1204829342484537384

  # --- PORTAINER ---
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    ports:
      - "192.168.50.100:9443:9443"
      - "192.168.50.100:9000:9000"

  # --- PI-HOLE ---
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - "192.168.50.100:53:53/tcp"
      - "192.168.50.100:53:53/udp"
      - "192.168.50.100:8080:80/tcp"
    environment:
      # AÑADE ESTA LÍNEA PARA AUTORIZAR A HOMEPAGE A LEER LA API v6 
      - REMS_ALLOWED_HOSTS=192.168.50.100,192.168.50.100:8080,localhost
      - TZ=Europe/Madrid
      - WEBPASSWORD=Pacopicopoco.7
    volumes:
      - ./data/pihole:/etc/pihole
      - ./data/dnsmasq.d:/etc/dnsmasq.d

  # --- HOMEPAGE ---
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    ports:
      - "192.168.50.100:3000:3000"
    volumes:
      - ./data/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #  Mapea toda la raíz del host de la misma forma
      - /:/mnt/host:ro
    environment:
      - TZ=Europe/Madrid
      - HOMEPAGE_ALLOWED_HOSTS=192.168.50.100,192.168.50.100:3000

# --- GLANCES ---
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: always
    pid: host
    privileged: true
    networks:
      - default # <-- ESTO ES CLAVE para que Homepage lo vea internamente
    environment:
      - GLANCES_OPT=-w
      - TZ=Europe/Madrid
      - LANG=es_ES.UTF-8
      - GLANCES_HOST_MOUNT=/mnt/host
      - PREFIX_PROCFS=/mnt/host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/mnt/host:ro
      - /etc/os-release:/etc/os-release:ro

  # --- FILEBROWSER ---
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    ports:
      - "192.168.50.100:8082:80" # Cambia el puerto si el 8082 ya está ocupado
    volumes:
      - /home:/srv # Acceso directo a tu partición de 1TB del servidor
      - ./data/filebrowser/config.json:/etc/filebrowser.json
      - ./data/filebrowser/database.db:/database.db
    environment:
      - TZ=Europe/Madrid

  # --- IMMICH: SERVIDOR DE FOTOS ---
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    volumes:
      - ./data/immich/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_DATA_LOCATION=immich_db
      - DB_DATABASE_NAME=immich
      - DB_USERNAME=postgres
      - DB_PASSWORD=immich_secure_pass
      - DB_HOSTNAME=immich-database
      - REDIS_HOSTNAME=immich-redis
      - IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
    ports:
      - "192.168.50.100:2283:2283"
    depends_on:
      - immich-database
      - immich-redis
    restart: always

  # --- IMMICH: INTELIGENCIA ARTIFICIAL ---
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_machine_learning
    volumes:
      - ./data/immich/cache:/cache
    restart: always

  # --- IMMICH: BASE DE DATOS OFICIAL ---
  immich-database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich_database
    environment:
      - POSTGRES_DB=immich
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=immich_secure_pass
    volumes:
      - immich_db:/var/lib/postgresql/data
    restart: always

  # --- IMMICH: REDIS ---
  immich-redis:
    image: redis:7-alpine
    container_name: immich_redis
    restart: always
