version: '3'
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.     #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Spain
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /home/inhumano/arr/Files/AppData/Config/Homarr/configs:/app/data/configs
      - /home/inhumano/arr/Files/AppData/Config/Homarr/icons:/app/public/icons
      - /home/inhumano/arr/Files/AppData/Config/Homarr/data:/data
    ports:
      - "7575:7575"