#services:
#  jellyfin:
#    image: lscr.io/linuxserver/jellyfin:latest
#    container_name: jellyfin
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Madrid
#      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
#    volumes:
#      - /home/inhumano/arr/Files/AppData/Config/Jellifin/config:/config
#      - /home/inhumano/arr/data/media/tv:/data/tvshows
#      - /home/inhumano/arr/data/media/movies:/data/movies
#    ports:
#      - 8096:8096
#      - 8920:8920 #optional
#      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
#    restart: always

version: "3.7"

services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK=002
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Jellifin/config:/config
      - /home/inhumano/arr/data/media:/data
    restart: always
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK=002
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Jellyseerr/config:/config
    restart: always
