version: "3.7"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Radarr:/config
      - /home/inhumano/arr/data:/data
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Sonarr:/config
      - /home/inhumano/arr/data:/data
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    ports:
      - "8686:8686"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Lidarr:/config
      - /home/inhumano/arr/data:/data
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    ports:
      - "8787:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Readarr:/config
      - /home/inhumano/arr/data:/data
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    restart: always
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Bazarr:/config
      - /home/inhumano/arr/data:/data  
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: always
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Prowlarr:/config
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK=002
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Jellifin/config:/config
      - /home/inhumano/arr/data/media:/data
    restart: always
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK=002
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Jellyseerr/config:/config
    restart: always
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Spain
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /home/inhumano/arr/Files/AppData/Config/Homarr/configs:/app/data/configs
      - /home/inhumano/arr/Files/AppData/Config/Homarr/icons:/app/public/icons
      - /home/inhumano/arr/Files/AppData/Config/Homarr/data:/data
    ports:
      - "7575:7575"
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Spain
      - PLEX_CLAIM_TOKEN
      - PLEX_ADVERTISE_URL
      - PLEX_NO_AUTH_NETWORKS
      - PLEX_BETA_INSTALL=false
      - PLEX_PURGE_CODECS=false
    restart: always
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Plex/configs:/app/data/configs
      - /home/inhumano/arr/Files/AppData/Config/Plex/transcode:/transcode
      - /home/inhumano/arr/data/media:/data
  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: always
    user: 1000:1000
    volumes:
        - /home/inhumano/JDownloader:/opt/JDownloader/app/cfg
        - /home/inhumano/Descargas:/opt/JDownloader/Downloads
        - /home/inhumano/JDownloader/logs:/opt/JDownloader/app/logs #optional
        - /home/inhumano/JDownloader/extensions:/opt/JDownloader/app/extensions #optional
    environment:
            MYJD_USER: ruben.peralta.jimenez@gmail.com #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_PASSWORD: Descargas #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_DEVICE_NAME: Pikachu #optional
    ports:
        - 3129:3129
  dash:
    image: mauricenino/dashdot:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Spain
    privileged: true
    ports:
      - 80:3001
    volumes:
      - /:/mnt/host:ro




#  sabnzbd:
#    container_name: sabnzbd
#    image: ghcr.io/hotio/sabnzbd:latest
#    restart: always
#    logging:
#      driver: json-file
#    ports:
#      - 8080:8080
#      - 9090:9090
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Madrid
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /home/inhumano/docker/appdata/sabnzbd:/config
#      - /home/inhumano/data/usenet:/data/usenet:rw
#  deluge:
#    image: lscr.io/linuxserver/deluge:latest
#    container_name: deluge
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Madrid
#      - DELUGE_LOGLEVEL=error #optional
#    volumes:
#      - /home/inhumano/docker/appdata/deluge/config:/config
#      - /home/inhumano/data/torrents:/data/torrents
#    ports:
#      - 8112:8112
#      - 6881:6881
#      - 6881:6881/udp
#      - 58846:58846 #optional
#    restart: always
