version: "3.7"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Radarr:/config
      - /home/inhumano/arr/data:/data
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Sonarr:/config
      - /home/inhumano/arr/data:/data
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    ports:
      - "8686:8686"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Lidarr:/config
      - /home/inhumano/arr/data:/data
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr:latest
    ports:
      - "8787:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Readarr:/config
      - /home/inhumano/arr/data:/data
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: always
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Bazarr:/config
      - /home/inhumano/arr/data:/data  
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: always
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Prowlarr:/config
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:latest
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK=002
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Jellifin/config:/config
      - /home/inhumano/arr/data/media:/data
    restart: always
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr:latest
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK=002
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Jellyseerr/config:/config
    restart: always
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /home/inhumano/arr/Files/AppData/Config/Homarr/configs:/app/data/configs
      - /home/inhumano/arr/Files/AppData/Config/Homarr/icons:/app/public/icons
      - /home/inhumano/arr/Files/AppData/Config/Homarr/data:/data
    ports:
      - "7575:7575"
  dash:
    image: mauricenino/dashdot:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    privileged: true
    ports:
      - 80:3001
    volumes:
      - /:/mnt/host:ro
  filebrowser:
    image: hurlenko/filebrowser:latest
    container_name: filebrowser
    restart: always
    ports:
      - 8123:8080
    volumes:
      - /home/inhumano/:/data
      - /home/inhumano/filebrowser:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
  jdownloader:
    image: jaymoulin/jdownloader:latest
    container_name: jdownloader
    restart: always
    user: 1000:1000
    volumes:
        - /home/inhumano/JDownloader:/opt/JDownloader/app/cfg
        - /home/inhumano/Descargas:/opt/JDownloader/Downloads
        - /home/inhumano/JDownloader/logs:/opt/JDownloader/app/logs #optional
        - /home/inhumano/JDownloader/extensions:/opt/JDownloader/app/extensions #optional
    environment:
            MYJD_USER: ruben.peralta.jimenez@gmail.com #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_PASSWORD: Descargas #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_DEVICE_NAME: Pikachu #optional
    ports:
        - 3129:3129
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "5080:80/tcp"
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'pito'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      containers:
        ipv4_address: 172.20.0.7

networks:
  containers:
    ipam:
      config:
        - subnet: 172.20.0.0/60
#  sabnzbd:
#    container_name: sabnzbd
#    image: ghcr.io/hotio/sabnzbd:latest
#    restart: always
#    logging:
#      driver: json-file
#    ports:
#      - 8080:8080
#      - 9090:9090
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Madrid
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /home/inhumano/docker/appdata/sabnzbd:/config
#      - /home/inhumano/data/usenet:/data/usenet:rw
#  deluge:
#    image: lscr.io/linuxserver/deluge:latest
#    container_name: deluge
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Madrid
#      - DELUGE_LOGLEVEL=error #optional
#    volumes:
#      - /home/inhumano/docker/appdata/deluge/config:/config
#      - /home/inhumano/data/torrents:/data/torrents
#    ports:
#      - 8112:8112
#      - 6881:6881
#      - 6881:6881/udp
#      - 58846:58846 #optional
#    restart: always
