version: "3.7"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Spain
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Radarr:/config
      - /home/inhumano/arr/data:/data
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Spain
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Sonarr:/config
      - /home/inhumano/arr/data:/data
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    restart: always
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Spain
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Bazarr:/config
      - /home/inhumano/arr/data:/data
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: always
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Spain
    volumes:
      - /home/inhumano/arr/Files/AppData/Config/Prowlarr:/config
#  sabnzbd:
#    container_name: sabnzbd
#    image: ghcr.io/hotio/sabnzbd:latest
#    restart: always
#    logging:
#      driver: json-file
#    ports:
#      - 8080:8080
#      - 9090:9090
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Spain
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /home/inhumano/docker/appdata/sabnzbd:/config
#      - /home/inhumano/data/usenet:/data/usenet:rw
#  deluge:
#    image: lscr.io/linuxserver/deluge:latest
#    container_name: deluge
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Spain
#      - DELUGE_LOGLEVEL=error #optional
#    volumes:
#      - /home/inhumano/docker/appdata/deluge/config:/config
#      - /home/inhumano/data/torrents:/data/torrents
#    ports:
#      - 8112:8112
#      - 6881:6881
#      - 6881:6881/udp
#      - 58846:58846 #optional
#    restart: always
